apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2025-08-06T10:03:21Z"
  creationTimestamp: "2025-08-06T10:03:21Z"
  generateName: deployment-1-9fbbdbffd-
  generation: 1
  labels:
    app: deployment-1
    app.kubernetes.io/managed-by: cloud-console
    pod-template-hash: 9fbbdbffd
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/restartedAt: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"5c2750d8-5275-482d-ab3b-272a5973f138"}: {}
      f:spec:
        f:containers:
          k:{"name":"nginx-1"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:ephemeral-storage: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:ephemeral-storage: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:capabilities:
                .: {}
                f:drop: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:seccompProfile:
            .: {}
            f:type: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-08-06T10:03:21Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.45.0.149"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2025-08-06T10:06:40Z"
  name: deployment-1-9fbbdbffd-cfmvg
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: deployment-1-9fbbdbffd
    uid: 5c2750d8-5275-482d-ab3b-272a5973f138
  resourceVersion: "1754474800786127000"
  uid: 5f6b0bdf-b122-488f-b329-b15fb93e4c6a
spec:
  containers:
  - image: gcr.io/nagpassignment-468019/node-app:latest
    imagePullPolicy: Always
    name: nginx-1
    resources:
      limits:
        ephemeral-storage: 1Gi
      requests:
        cpu: 500m
        ephemeral-storage: 1Gi
        memory: 2Gi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5bhbv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gk3-demo-2025-nap-d4harp0y-c1640c50-mqx2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: gke.io/optimize-utilization-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: kubernetes.io/arch
    operator: Equal
    value: amd64
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5bhbv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T10:03:23Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T10:03:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T10:03:21Z"
    message: 'containers with unready status: [nginx-1]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T10:03:21Z"
    message: 'containers with unready status: [nginx-1]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T10:03:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: gcr.io/nagpassignment-468019/node-app:latest
    imageID: ""
    lastState: {}
    name: nginx-1
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'Back-off pulling image "gcr.io/nagpassignment-468019/node-app:latest":
          ErrImagePull: failed to pull and unpack image "gcr.io/nagpassignment-468019/node-app:latest":
          failed to resolve reference "gcr.io/nagpassignment-468019/node-app:latest":
          failed to authorize: failed to fetch oauth token: unexpected status from
          GET request to https://gcr.io/v2/token?scope=repository%3Anagpassignment-468019%2Fgcr.io%2Fnode-app%3Apull&scope=repository%3Anagpassignment-468019%2Fnode-app%3Apull&service=gcr.io:
          403 Forbidden'
        reason: ImagePullBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5bhbv
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.128.0.15
  hostIPs:
  - ip: 10.128.0.15
  phase: Pending
  podIP: 10.45.0.149
  podIPs:
  - ip: 10.45.0.149
  qosClass: Burstable
  startTime: "2025-08-06T10:03:21Z"
