apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  selector:
    app: deployment-1
  ports:
    - protocol: TCP
      port: 80         # Exposed port
      targetPort: 3000 # Port your API app is running on
  type: LoadBalancer